version: '3.8'
services:

  db:
    container_name: db_pg
    restart: always
    image: postgres:13
    ports:
      - 2021:5432
    environment:
      POSTGRES_USER: whatsyourfinances
      POSTGRES_PASSWORD: f1n4nc4s
      POSTGRES_DB: finances
    networks:
      - whatsYourFinanceNetwork

  whatsapp_web_api:
    restart: always
    container_name: whatsapp_web_api
    image: pedromachado2298/whatsapp-web-api:1.0 # Pull the image from Docker Hub
    ports:
      - "3636:3000"
    environment:
      # - API_KEY=your_global_api_key_here  # OPTIONAL
      - BASE_WEBHOOK_URL=http://whats-your-finances:3001/api/whatsapp/webhook
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=TRUE # OPTIONAL, NOT RECOMMENDED FOR PRODUCTION SE DESATIVAR DA XABLAU
      - MAX_ATTACHMENT_SIZE=5000000 # IN BYTES
      - SET_MESSAGES_AS_SEEN=TRUE # WILL MARK THE MESSAGES AS READ AUTOMATICALLY
      # ALL CALLBACKS: auth_failure|authenticated|call|change_state|disconnected|group_join|group_leave|group_update|loading_screen|media_uploaded|message|message_ack|message_create|message_reaction|message_revoke_everyone|qr|ready|contact_changed
      - DISABLED_CALLBACKS=message_ack|message_create|message_reaction|unread_count|message_edit|message_ciphertext|auth_failure|authenticated|call|change_state|disconnected|group_join|group_leave|group_update|loading_screen|message_reaction|message_edit|message_ciphertext|message_revoke_everyone|message_revoke_me|qr|ready|contact_changed|chat_removed|chat_archived|unread_count  # PREVENT SENDING CERTAIN TYPES OF CALLBACKS BACK TO THE WEBHOOK
      - ENABLE_SWAGGER_ENDPOINT=TRUE # OPTIONAL, ENABLES THE /api-docs ENDPOINT
      # - RATE_LIMIT_MAX=1000 # OPTIONAL, THE MAXIUM NUMBER OF CONNECTIONS TO ALLOW PER TIME FRAME
      # - RATE_LIMIT_WINDOW_MS=1000 # OPTIONAL, TIME FRAME FOR WHICH REQUESTS ARE CHECKED IN MS
      # - WEB_VERSION='2.2328.5' # OPTIONAL, THE VERSION OF WHATSAPP WEB TO USE
      # - WEB_VERSION_CACHE_TYPE=none # OPTIONAL, DETERMINES WHERE TO GET THE WHATSAPP WEB VERSION(local, remote or none), DEFAULT 'none'
      # - RECOVER_SESSIONS=TRUE # OPTIONAL, SHOULD WE RECOVER THE SESSION IN CASE OF PAGE FAILURES
    volumes:
      - ./sessions:/usr/src/app/sessions # Mount the local ./sessions/ folder to the container's /usr/src/app/sessions folder
    networks:
      - whatsYourFinanceNetwork

  whats-your-finances:
    restart: always
    image: pedromachado2298/whats_your_finance:1.0
    ports:
      - 3001:3001
    environment:
      - CALLBACL_URL_WHATSAPP=http://whatsapp_web_api:3000

    networks:
      - whatsYourFinanceNetwork
    depends_on:
      - db
      - whatsapp_web_api

networks:
  whatsYourFinanceNetwork: